#! /bin/sh

curl -s "http://www.bing.com/search?q=$1" | grep -o -e '<span class="sb_count" id="count">1-10 sur .* résultats</span>' | perl -p -e 's/<span class="sb_count" id="count">1-10 sur (.*) résultats<\/span>/$1/;' | tr -d " "